# DigitalOcean App Platform configuration for README-MCP
name: readme-mcp
region: nyc

services:
- name: web
  source_dir: /
  github:
    repo: your-username/readme-mcp
    branch: main
    deploy_on_push: true
  
  run_command: uvicorn readme_mcp.main:app --host 0.0.0.0 --port $PORT
  
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  
  routes:
  - path: /
    preserve_path_prefix: true
  
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  envs:
  - key: PYTHONPATH
    value: /app/src
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: PORT
    value: "8080"
  
  # Auto-scaling configuration
  autoscaling:
    min_instance_count: 1
    max_instance_count: 5
    metrics:
      cpu:
        percent: 70
      memory:
        percent: 80

# Optional: Add a database for caching (Redis)
databases:
- name: redis-cache
  engine: REDIS
  version: "7"
  size: db-s-dev-database